// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIStNMts3a_lRU3__GlnmV6dSCHoS-tB4',
    appId: '1:121276670790:web:89b27224cca86b58eebb47',
    messagingSenderId: '121276670790',
    projectId: 'task-tracker-c4a4e',
    authDomain: 'task-tracker-c4a4e.firebaseapp.com',
    storageBucket: 'task-tracker-c4a4e.appspot.com',
    measurementId: 'G-0TKZLS25JY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNs-CxyvXENJjZD8HY0yJtH8oyW6ulewg',
    appId: '1:121276670790:ios:51c3f09e7ac97cb6eebb47',
    messagingSenderId: '121276670790',
    projectId: 'task-tracker-c4a4e',
    storageBucket: 'task-tracker-c4a4e.appspot.com',
    iosBundleId: 'com.goharamin.taskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIStNMts3a_lRU3__GlnmV6dSCHoS-tB4',
    appId: '1:121276670790:web:92b0bfdfdd323aa8eebb47',
    messagingSenderId: '121276670790',
    projectId: 'task-tracker-c4a4e',
    authDomain: 'task-tracker-c4a4e.firebaseapp.com',
    storageBucket: 'task-tracker-c4a4e.appspot.com',
    measurementId: 'G-YY3TK0CYMK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNs-CxyvXENJjZD8HY0yJtH8oyW6ulewg',
    appId: '1:121276670790:ios:51c3f09e7ac97cb6eebb47',
    messagingSenderId: '121276670790',
    projectId: 'task-tracker-c4a4e',
    storageBucket: 'task-tracker-c4a4e.appspot.com',
    iosBundleId: 'com.goharamin.taskTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdeiBvGQQX1d-Ef0Wzl2jrvO3hp094q4',
    appId: '1:121276670790:android:7504c30c9732ea52eebb47',
    messagingSenderId: '121276670790',
    projectId: 'task-tracker-c4a4e',
    storageBucket: 'task-tracker-c4a4e.appspot.com',
  );

}